### ISSUE TITLE
Improve github workflow

### ISSUE THREAD

**Issue by DrakeEntity** [Py-Contributors/OpenCv-tutorial#2]
Improve GitHub workflow

* `.github/workflows`
    - greetings.yml
    - label.yml

**Comment by percygautam** [comment]
Hi, can you elaborate on the work that needs to be done?

**Comment by bislara** [comment]
Hey, I would like to work on this. I guess this labeller is for the issues and greeting for the first time contributor. 
I have worked on this also. Can you assign it to me?

**Comment by codePerfectPlus** [comment]
@bislara Ya sure
