### ISSUE TITLE
Face Detection using OpenCV DNN Module

### ISSUE THREAD

**Issue by harshit-saraswat** [Py-Contributors/OpenCv-tutorial#5]
Haarcascades are pretty old and perform a little worse than other solutions out there. I was wondering if I could do a Face Detection using OpenCV DNN Module tutorial/code and add it on as a PR during HacktoberFest. Will it work?

**Comment by codePerfectPlus** [comment]
Ya, it will count

- [ ] Assigning the task to @harshit-saraswat 

Happy Coding,

**Comment by harshit-saraswat** [comment]
Thanks! @codePerfectPlus
