### ISSUE TITLE
Cropping images Dynamically

### ISSUE THREAD

**Issue by Pranjalmishra30** [Py-Contributors/OpenCv-tutorial#6]
**Title** - Cropping Images using mouse with the help of OpenCV library in python

**what will change** -  There is no code for this currently

**Assignees** - 

### Type of Issue 
Please add/delete options that are not relevant.
- [x] Adding New Code

### Programming Language
Please add/delete options that are not relevant.
- [x] Python

**Comment by codePerfectPlus** [comment]
- [x] Issue assigned to @Pranjalmishra30 

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!
Happy Coding

**Comment by Pranjalmishra30** [comment]
Okk thanks a lot !

**Comment by codePerfectPlus** [comment]
2. Core operations
