### ISSUE TITLE
Shape Contouring

### ISSUE THREAD

**Issue by Pranjalmishra30** [Py-Contributors/OpenCv-tutorial#7]
**Title** - Finding Contours of Shapes using thresholding in OpenCV-Python

**what will change** -  There is no code for this currently

**Assignees** - 

### Type of Issue 
Please add/delete options that are not relevant.
- [x] Adding New Code

### Programming Language
Please add/delete options that are not relevant.
- [x] Python

**Comment by Pranjalmishra30** [comment]
Can this issue be assigned to me ?

**Comment by Pranjalmishra30** [comment]
Thanks

**Comment by Pranjalmishra30** [comment]
Which folder should i commit to , or should i make a new folder please suggest.

**Comment by codePerfectPlus** [comment]
Create a new folder and your both Pull there
- Image operations 
@Pranjalmishra30

**Comment by codePerfectPlus** [comment]
Create a new folder and pull your both of change there
- Image operations 

@Pranjalmishra30

**Comment by Pranjalmishra30** [comment]
Do you mean the earlier issue https://github.com/Py-Contributors/OpenCv-tutorial/issues/6#issue-709999845
So to confirm both Image cropping and Shape contouring in a new folder - Image operations

**Comment by codePerfectPlus** [comment]
yes confirm
